config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"

Rails.application.routes.draw do
  devise_for :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "categories#index"

  namespace :api do
    namespace :v1 do
      resources :categories, only: [:show]
      resources :sops, only: [:index, :show]
      resources :tokens, only: [:create]
    end
  end

  # resources :sops, except: [:index] do
  resources :sops do
    collection do
      get :download
    end
  end

  resources :categories do
    collection do
      post :move
      post :move_sop
    end
  end

  resources :searches, only: [:index]

  resources :uploads, only: [:index] do
    collection do
      post :validate
      post :import
    end
  end

  resource :users do
    collection do
      post :update_locale
    end
  end

  if Rails.env.production?
    authenticate :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => "/sidekiq"
    end
  else
    mount Sidekiq::Web => "/sidekiq"
  end
end

app/models/sop.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: sops
#
#  id          :bigint           not null, primary key
#  name        :string
#  file        :string
#  tags        :text             default([]), is an Array
#  category_id :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  description :text
#  is_deleted  :boolean          default(FALSE)
#

class Sop < ApplicationRecord
  include ::SoftDeletable
  searchkick \
    word_middle: [:name, :tags, :description],
    text_middle: [:name, :tags, :description]

  mount_uploader :file, FileUploader

  belongs_to :category, optional: true

  validates :name, presence: true
  validates :name, uniqueness: { case_sensitive: false, conditions: -> { where(is_deleted: false) } }

  delegate :identifier, to: :file, allow_nil: true

  after_commit ->  { EsFileIndexJob.perform_later(id) }, \
                      if: :es_file_index?,
                      on: [:create, :update]

  def with_attachment(path, file)
    whitelist_files = /^[https?:\/\/]?[\S]+\/\S+\.(?:pdf|zip)$/

    return if File.extname(file).blank? || file.blank?
    return self.remote_file_url = file if file.scan(whitelist_files).present?

    File.open("#{path}/#{file}") { |f| yield f } if File.exist?("#{path}/#{file}")
  end

  def search_data
    {
      name: name,
      tags: tags,
      description: description
    }
  end

  def category_name
    category.try(:name) || ""
  end

  def self.create_record(data)
    category_id = Category.find_by(name: data[:category_name]).try(:id)
    sop = new(name: data[:name], description: data[:description], tags: data[:tags], category_id: category_id)

    if data[:file].present?
      File.open(data[:file]) { |f| sop.file = f }
    end

    sop.save
  end

  def self.build_record(data)
    category_id = Category.find_by(name: data[:category_name]).try(:id)
    sop = new(name: data[:name], description: data[:description], tags: data[:tags], category_id: category_id)

    if data[:file].present?
      File.open(data[:file]) { |f| sop.file = f }
    end

    sop
  end

  private
    def es_file_index?
      ENV["ES_FILE_INDEXABLE"] == "true"
    end
end

app/controllers/api/v1/sops_controller.rb
# frozen_string_literal: true

module Api::V1
  class SopsController < ApiController
    before_action :check_secret_key

    def index
      @search = SearchService.text_search(sop_params)
      render json: @search.as_json(methods: [:model_name])
    end

    def show
      @sop = Sop.find_by(id: params[:id])
      render json: @sop
    end

    private
      def sop_params
        params.permit(:q, :page)
      end

      def token
        auth = request.headers["Authorization"]
        @token ||= auth.split.last if auth
      end

      def check_secret_key
        if token != Rails.application.credentials.app[:server_secret_key_base]
          render json: { error: t(:unauthorize), status: :bad_request }
        end
      end
  end
end

app/controllers/sops_controller.rb
# frozen_string_literal: true

class SopsController < ApplicationController
  include Pagy::Backend

  def index
    @pagy, @sops = pagy(Sop.includes(:category))
  end

  def show
    @sop = Sop.find(params[:id])
  end

  def new
    @sop = Sop.new(category_id: params[:category_id])
  end

  def create
    data = sop_params
    data[:tags] = data[:tags].split(" ")

    @sop = Sop.new(data)
    if @sop.save
      PushNotificationJob.perform_later("all", data: sop_notification_data, priority: "high")
      redirect_to sop_path(@sop)
    else
      flash.now[:alert] = @sop.errors.full_messages
      render :new
    end
  end

  def edit
    @sop = Sop.find(params[:id])
  end

  def update
    @sop = Sop.find(params[:id])
    data = sop_params
    data[:tags] = data[:tags].split(" ")

    if @sop.update(data)
      if params[:sop][:remove_file] == "1"
        @sop.remove_file!
        @sop.save
      end

      redirect_to sop_path(@sop)
    else
      flash.now[:alert] = @sop.errors.full_messages
      render :edit
    end
  end

  def destroy
    @sop = Sop.find(params[:id])
    category = @sop.category
    @sop.destroy

    url = category.present? ? category_path(category) : categories_path
    redirect_to url
  end

  def download
    send_file "#{Rails.root}/public/#{params[:file]}", disposition: "attachment"
  end

  private
    def sop_params
      params.require(:sop).permit(
        :name, :category_id, :file, :tags, :description, :remove_file
      )
    end

    def sop_notification_data
      {
        itemId: @sop.id,
        title: t(:notif_title),
        body: t(:notif_body_with_name, sop_name: @sop.name)
      }
    end

    def notification_data
      {
        title: t(:notif_title),
        body: t(:notif_body)
      }
    end
end

app/helpers/sops_helper.rb
# frozen_string_literal: true

module SopsHelper
  def name(fileurl)
    File.basename(fileurl).split("-", 2)[1]
  end

  def return_url
    @sop.category_id.present? ? category_path(@sop.category_id) : categories_path
  end
end

app/views/sops/_form.html.haml
.w-50.view-center
  = simple_form_for @sop, html: { id: 'sop-form' } do |f|
    = f.input :name, label: t(:name)
    = f.input :description, label: t(:description)
    .form-group
      %label.form-control-label{ for: 'sop[tags]'}= "#{t(:tags)}:"
      %input#sop-tags.form-control{ name: 'sop[tags]', value: @sop.tags.join(' ') }
    .form-group
      %label.form-control-label{ for: 'sop[category_id]' }= t(:category)
      %select.form-control{ disabled: true }
        %option= @sop.category.try(:name)
      = f.hidden_field :category_id, type: :hidden


    = f.input :file, label: t(:file), as: :file, input_html: { accept: '.pdf, .zip' }

    - unless @sop.file.file.nil?
      .flex-row
        = f.hidden_field :remove_file, class: 'destroy'
        = link_to '#', class: "remove-file", style: @sop.file.file.nil? ? 'display: none': '' do
          %i.far.fa-trash-alt{style: 'color: red; margin-right: 5px'}

        %small.form-text.text-muted= name(@sop.file.path)

    .actions{style: 'margin-top: 30px'}
      = f.button :submit, class: 'btn btn-primary', value: t(:save)
      = link_to t(:cancel), cancel_url, class: 'btn btn-secondary'

app/views/sops/_sops.html.haml
- @sops.each do |sop|
  %tr
    %td
      = link_to sop.name.html_safe, sop_path(sop)
    %td= sop.tags.join(', ')
    %td
      - if sop.file_url.present?
        = link_to sop.file_url, download: name(sop.file.path), style:'color: #007bff' do
          %span= name(sop.file.path)
          %i.fas.fa-download

    %td= sop.category_name
    %td
      = link_to t(:edit), edit_sop_path(sop), class: 'badge badge-info'
      = "/"
      = link_to t(:delete), sop_path(sop), method: :delete, class: 'badge badge-danger', :data => {confirm: t(:confirm_delete, resource: 'sop')}

app/views/sops/edit.html.haml
%nav.navbar.navbar-expand-lg.navbar-light.bg-light
  .container-fluid
    %h3= t(:sop_edit)

= render 'form', cancel_url: sop_path(@sop)

app/views/sops/index.html.haml
%nav.navbar.navbar-expand-lg.navbar-light.bg-light
  .container-fluid
    %h3= t(:sop)
    = render 'shared/search_form'
    %ul.navbar-nav.ml-auto
      %li.nav-item.mr-sm-2
        = link_to new_sop_path, class: 'btn btn-primary' do
          %i.fas.fa-plus
      %li.nav-item
        = link_to upload_sops_path, class: 'btn btn-primary' do
          %i.fas.fa-file-archive


- if @sops.present?
  %table.table.table-hover.medium-width
    %thead
      %tr
        %th= t(:name)
        %th= t(:tags)
        %th= t(:file)
        %th= t(:category)
        %th

    %tbody#body-content
      = render 'sops'

- if @pagy.pages > 1
  .pagy-wrapper.d-flex.justify-content-center
    != pagy_bootstrap_nav(@pagy)

app/views/sops/new.html.haml
%nav.navbar.navbar-expand-lg.navbar-light.bg-light
  .container-fluid
    %h3= t(:sop_new)

= render 'form', cancel_url: return_url

app/views/sops/show.html.haml
%nav.navbar.navbar-expand-lg.navbar-light.bg-light
  .container-fluid
    %h3= @sop.name
    %ul.navbar-nav.ml-auto
      %li.nav-item.mr-sm-2
        = link_to edit_sop_path(@sop), class: 'btn btn-primary' do
          %i.fas.fa-pen
      %li.nav-item
        = link_to sop_path(@sop), method: :delete, class: 'btn btn-danger', :data => {confirm: t(:confirm_delete, resource: 'sop')} do
          %i.fas.fa-trash

.container
  .row
    .col-sm-1= t(:name)
    .col-sm= @sop.name
  - if @sop.description.present?
    .row
      .col-sm-1= "#{t(:description)}:"
      .col-sm= simple_format @sop.description
  - if @sop.category.present?
    .row
      .col-sm-1= "#{t(:category)}:"
      .col-sm= link_to @sop.category_name, category_path(@sop.category)
  - if @sop.tags.size.positive?
    .row
      .col-sm-1= "#{t(:tags)}:"
      .col-sm
        - @sop.tags.each do |tag|
          .badge.badge-secondary= tag
  - unless @sop.file.file.nil?
    .row
      .col-sm-1= "#{t(:file)}:"
      .col-sm
        = link_to @sop.file.url, download: name(@sop.file.url) do
          = name(@sop.file.path)
          %i.fa.fa-download
  %br
  = link_to t(:go_back), return_url, class: 'btn btn-secondary'

app/views/sops/upload.html.haml
%nav.navbar.navbar-expand-lg.navbar-light.bg-light
  .container-fluid
    %h3= t("sidebar.import_sop")
    %ul.navbar-nav.ml-auto
      = link_to asset_path("sop-import.zip"), download: "sop-import-sample.zip", class: 'btn btn-secondary', 'data-toggle' => :tooltip, title: t(:download) do
        %i.fas.fa-download

= form_with(url: import_sops_path, method: :post, multipart: true) do |f|
  .col-auto
    .form-group
      %label{ for: :zip_file }= t(:import_option)
      = f.file_field(:zip_file, class: "form-control-file", accept: "application/zip")
      - if flash[:alert].present?
        .text-danger= flash[:alert]
  %br
  .col-auto
    = f.submit t(:import), class: 'btn btn-primary'