config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"

Rails.application.routes.draw do
  devise_for :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "categories#index"

  namespace :api do
    namespace :v1 do
      resources :categories, only: [:show]
      resources :sops, only: [:index, :show]
      resources :tokens, only: [:create]
    end
  end

  # resources :sops, except: [:index] do
  resources :sops do
    collection do
      get :download
    end
  end

  resources :categories do
    collection do
      post :move
      post :move_sop
    end
  end

  resources :searches, only: [:index]

  resources :uploads, only: [:index] do
    collection do
      post :validate
      post :import
    end
  end

  resource :users do
    collection do
      post :update_locale
    end
  end

  if Rails.env.production?
    authenticate :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => "/sidekiq"
    end
  else
    mount Sidekiq::Web => "/sidekiq"
  end
end

app/views/shared/_lang_switch.html.haml
.dropdown
  %button#dropdownMenuButton.btn.btn-light.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :type => "button"}
    = lang.name
  .dropdown-menu{"aria-labelledby" => "dropdownMenuButton"}
    - lang.choices.each do |l|
      = link_to l[:name], l[:url], class: 'dropdown-item'

app/views/shared/_notify_message.html.haml
- if flash[:notice]
  .alert.alert-success.notify-message
    %button.close{type: 'button', 'data-dismiss' => 'alert', 'aria-label' => 'Close'}
    = flash[:notice]
- if flash[:alert]
  .alert.alert-danger.notify-message
    %button.close{type: 'button', 'data-dismiss' => 'alert', 'aria-label' => 'Close'}
    = flash[:alert]

:javascript
  setTimeout(function() {
    $( ".alert" ).fadeOut( "slow" )
  }, 3000);

app/views/shared/_search_form.html.haml
.col-sm-6.mx-auto
  %form{action: searches_path, method: :get}
    .row
      .input-group
        .input-group-prepend
          %span.input-group-text
            %i.fa.fa-search
        %input.form-control{name: :q, value: params[:q], placeholder: t("search_eoc")}
        .input-group-append
          %button.btn.btn-secondary{type: :submit}= t(:search)

app/views/shared/_sidebar.html.haml
%nav#sidebar
  #sidebarCollapse.sidebar-header
    %h3
      Emergency Operation Center

    %strong EOC
    %i.fas.fa-align-left

  %ul.list-unstyled.components
    %li
      = link_to root_path do
        %i.fas.fa-home
        = t('sidebar.home')
    %li
      = link_to uploads_path do
        %i.fas.fa-file-import
        = t('sidebar.import_wizard')
    %li
      = link_to destroy_user_session_path, method: :delete do
        %i.fas.fa-key
        = t('sidebar.logout')

  .switch-language
    = simple_form_for(current_user, url: update_locale_users_path, method: :post, remote: true, html: { id: "switch-language" }) do |f|
      %label= switch_language_data[:label]
      = f.hidden_field :locale, value: switch_language_data[:locale]
      = f.submit switch_language_data[:submit_label], class: "btn btn-link language"

  .copyright
    © 2019 InSTEDD