config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"

Rails.application.routes.draw do
  devise_for :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "categories#index"

  namespace :api do
    namespace :v1 do
      resources :categories, only: [:show]
      resources :sops, only: [:index, :show]
      resources :tokens, only: [:create]
    end
  end

  # resources :sops, except: [:index] do
  resources :sops do
    collection do
      get :download
    end
  end

  resources :categories do
    collection do
      post :move
      post :move_sop
    end
  end

  resources :searches, only: [:index]

  resources :uploads, only: [:index] do
    collection do
      post :validate
      post :import
    end
  end

  resource :users do
    collection do
      post :update_locale
    end
  end

  if Rails.env.production?
    authenticate :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => "/sidekiq"
    end
  else
    mount Sidekiq::Web => "/sidekiq"
  end
end

app/controllers/searches_controller.rb
# frozen_string_literal: true

class SearchesController < ApplicationController
  include Pagy::Backend

  def index
    @results = SearchService.text_search(search_params)
    @pagy = Pagy.new_from_searchkick(@results)
  end

  private
    def search_params
      data = params.merge(per_page: 20)
      data[:q] = "*" unless data[:q].present?
      data
    end
end

app/helpers/searches_helper.rb
# frozen_string_literal: true

module SearchesHelper
  def hilite_name(sop)
    sop.try(:highlight).try(:name) ? sop.highlight.name.first : sop.name
  end

  def hilite_tags(sop)
    sop.try(:highlight).try(:tags) || sop.tags
  end
end

app/views/searches/_category_result.html.haml
%tr
  %td
    = link_to category_path(id: result.id) do
      %i.fa.fa-folder
      %span!= result.name
  %td
    = result.tags.join(', ')
  %td
    = link_to t(:edit), edit_category_path(id: result.id), class: 'badge badge-info'

app/views/searches/_sop_result.html.haml
%tr
  %td
    = link_to sop_path(id: result.id) do
      %i.far.fa-file
      %span= result.name
  %td
    = result.tags.join(' ')

  %td
    = link_to t(:edit), edit_sop_path(id: result.id), class: 'badge badge-info'
    = "/"
    = link_to t(:delete), sop_path(id: result.id), method: :delete, class: 'badge badge-danger', :data => {confirm: t(:confirm_delete, resource: 'sop')}

app/views/searches/index.html.haml
%nav.navbar.navbar-expand-lg.navbar-light.bg-light
  .container-fluid
    %h3= t(:search)
    = render 'shared/search_form'
    .ml-auto

- if @results.size.positive?
  %table.table.table-hover
    %thead
      %tr
        %th= t(:name)
        %th= t(:tags)
        %th

    %tbody#body-content
      - @results.each do |result|
        - if result.instance_of? Category
          = render 'category_result', result: result
        - else
          = render 'sop_result', result: result
- if @pagy.pages > 1
  .pagy-wrapper.d-flex.justify-content-center
    != pagy_bootstrap_nav(@pagy)