config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"

Rails.application.routes.draw do
  devise_for :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "categories#index"

  namespace :api do
    namespace :v1 do
      resources :categories, only: [:show]
      resources :sops, only: [:index, :show]
      resources :tokens, only: [:create]
    end
  end

  # resources :sops, except: [:index] do
  resources :sops do
    collection do
      get :download
    end
  end

  resources :categories do
    collection do
      post :move
      post :move_sop
    end
  end

  resources :searches, only: [:index]

  resources :uploads, only: [:index] do
    collection do
      post :validate
      post :import
    end
  end

  resource :users do
    collection do
      post :update_locale
    end
  end

  if Rails.env.production?
    authenticate :user, lambda { |u| u.admin? } do
      mount Sidekiq::Web => "/sidekiq"
    end
  else
    mount Sidekiq::Web => "/sidekiq"
  end
end

app/models/category.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: categories
#
#  id             :bigint           not null, primary key
#  name           :string
#  parent_id      :integer
#  lft            :integer          not null
#  rgt            :integer          not null
#  depth          :integer          default(0), not null
#  children_count :integer          default(0), not null
#  is_deleted     :boolean          default(FALSE)
#  tags           :text             default([]), is an Array
#

class Category < ApplicationRecord
  include ::SoftDeletable
  searchkick \
    text_middle: [:name, :tags],
    word_middle: [:name, :tags]

  # include Elasticsearch::Model
  # include Elasticsearch::Model::Callbacks

  has_many :sops, class_name: "Sop"

  validates :name, presence: true
  validates :name, uniqueness: { case_sensitive: false, conditions: -> { where(is_deleted: false) } }

  before_destroy :check_category

  acts_as_nested_set

  def is_empty?
    children.count.zero? && sops.count.zero?
  end

  def self.create_record(data, attachment_path = nil)
    parent_id = Category.find_by(name: data[:parent_name]).try(:id)
    create(name: data[:name], parent_id: parent_id)
  end

  def self.build_record(data)
    parent_id = Category.find_by(name: data[:parent_name]).try(:id)
    new(name: data[:name], parent_id: parent_id)
  end

  private
    def check_category
      unless is_empty?
        errors[:base] << I18n.t(:category_present)
        throw :abort
      end
    end
end

app/controllers/api/v1/categories_controller.rb
# frozen_string_literal: true

module Api::V1
  class CategoriesController < ApiController
    def show
      category = Category.find(params["id"])
      render json: { sops: category.sops,
                      children: category.children }
    end
  end
end

app/controllers/categories_controller.rb
# frozen_string_literal: true

class CategoriesController < ApplicationController
  include Pagy::Backend

  def index
    @sub_categories = Category.roots
    @sops = Sop.where(category_id: nil)
  end

  def new
    @category = Category.new(parent_id: params[:parent_id])
  end

  def create
    data = category_params
    data[:tags] = data[:tags].split(" ")

    @category = Category.new(data)
    if @category.save
      redirect_to category_path(@category)
    else
      flash.now[:alert] = @category.errors.full_messages
      render :new
    end
  end

  def show
    @category = Category.find(params[:id])
    @sub_categories = @category.children
    @sops = Sop.where(category_id: params[:id])
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    data = category_params
    data[:tags] = data[:tags].split(" ")

    if @category.update(data)
      redirect_to category_path(@category)
    else
      flash.now[:alert] = @category.errors.full_messages
      render :edit
    end
  end

  def move
    category = Category.find(move_params[:category_id])
    if category.update(parent_id: move_params[:parent_id])
      redirect_to redirect_url
    else
      flash.now[:alert] = category.errors.full_messages
    end
  end

  def move_sop
    sop = Sop.find(move_params[:sop_id])
    if sop.update(category_id: move_params[:parent_id])
      redirect_to redirect_url
    else
      flash.now[:alert] = sop.errors.full_messages
    end
  end

  def destroy
    @category = Category.find(params[:id])

    if @category.destroy
      redirect_to @category.child? ? category_path(@category.parent.id) : categories_path, flash: { notice: "The category was deleted." }
    else
      flash.now[:alert] = @category.errors.full_messages
    end
  end

  private
    def category_params
      params.require(:category).permit(:name, :parent_id, :tags)
    end

    def move_params
      params.require(:category).permit(:parent_id, :category_id, :sop_id)
    end

    def redirect_url
      move_params[:parent_id].present? ? category_path(move_params[:parent_id]) : categories_path
    end
end

app/helpers/categories_helper.rb
# frozen_string_literal: true

module CategoriesHelper
  def nested_li(objects, &block)
    objects = objects.order(:lft) if objects.is_a? Class

    return "" if objects.size == 0

    output = +"<ul><li id=#{objects.first.id}>"
    path = [nil]

    objects.each_with_index do |o, i|
      if o.parent_id != path.last
        if path.include?(o.parent_id)
          while path.last != o.parent_id
            path.pop
            output << "</li></ul>"
          end
          output << "</li><li id=#{o.id}>"
        else
          path << o.parent_id
          output << "<ul style='list-style: none;'><li id=#{o.id}>"
        end
      elsif i != 0
        output << "</li><li id=#{o.id}>"
      end
      output << capture(o, path.size - 1, &block)
    end

    output << "</li></ul>" * path.length
    output.html_safe
  end
end

app/views/categories/_breadcrumb.html.haml
%nav{ 'aria-label' => 'breadcrumb' }
  %ol.breadcrumb
    - if @category.present?
      %li.breadcrumb-item
        = link_to 'Root', categories_path
      - @category.ancestors.each do |ancestor_category|
        %li.breadcrumb-item
          = link_to ancestor_category.name, category_path(ancestor_category.id)
      %li.breadcrumb-item.active{ 'aria-current' => 'page' }= @category.name
    - else
      %li.breadcrumb-item.active{ 'aria-current' => 'page' } Root

app/views/categories/_category_modal.html.haml
#category-modal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "categoryModal", :role => "dialog", :tabindex => "-1"}
  .modal-dialog{:role => "document"}
    .modal-content
      .modal-header
        %h5#exampleModalLabel.modal-title= t(:category_move)
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
      .modal-body
        %ul#category-list
          %li.root-category
            %span.category-item
              %i.fa.fa-folder
              Root
          = nested_li(Category.order(:lft)) do |category|
            %span.category-item
              %i.fa.fa-folder
              = category.name

      = form_tag '', id: 'move-category-form', class: 'modal-footer', method: :post, 'data-category-url' => move_categories_path, 'data-sop-url' => move_sop_categories_path, 'data-current-id' => params[:id] do
        %input#category-item{type: :hidden, name: 'category[category_id]'}
        %input#sop-item{type: :hidden, name: 'category[sop_id]'}
        %input#parent-category{type: :hidden, name: 'category[parent_id]'}
        %button.btn.btn-secondary{"data-dismiss" => "modal", :type => "button"}= t(:close)
        %button.btn.btn-primary{type: :submit}= t(:move)

app/views/categories/_form.html.haml
.w-50.view-center
  = simple_form_for @category, html: { id: 'category-form' } do |f|
    = f.input :name, label: t(:name)
    .form-group
      %label.form-control-label{ for: 'category[tags]'}= "#{t(:tags)}:"
      %input#category-tags.form-control{ name: 'category[tags]', value: @category.tags.join(' ') }
    .form-group
      %label.form-control-label{ for: 'sop[category_id]' }= t(:category_parent)
      %select.form-control{ disabled: true }
        %option= @category.parent.try(:name)
      = f.input :parent_id, as: :hidden, value: @category.parent_id

    .actions{style: 'margin-top: 30px'}
      = f.button :submit, class: 'btn btn-primary', value: t(:save)
      = link_to t(:cancel), url, class: 'btn btn-secondary'

app/views/categories/_item_lists.html.haml
%table.table
  %thead
    %tr
      %th= t(:name)
      %th= t(:tags)
      %th
  %tbody
    - @sub_categories.each do |category|
      %tr
        %td
          = link_to category_path(category.id) do
            %i.fa.fa-folder
            %span= category.name
        %td
          = category.tags.join(', ')
        %td
          = link_to t(:move), "#", class: 'badge badge-info', 'data-toggle' => :modal, 'data-target' => "#category-modal", 'data-id' => category.id, 'data-type' => 'category'
          \/
          = link_to t(:edit), edit_category_path(id: category.id), class: 'badge badge-info'
    - @sops.each do |sop|
      %tr
        %td
          = link_to sop_path(sop) do
            %i.far.fa-file
            %span= sop.name
        %td
          = sop.tags.join(', ')
        %td
          = link_to t(:move), "#", class: 'badge badge-info', 'data-toggle' => :modal, 'data-target' => "#category-modal", 'data-id' => sop.id, 'data-type' => 'sop'
          \/
          = link_to t(:edit), edit_sop_path(id: sop.id), class: 'badge badge-info'
          \/
          = link_to t(:delete), sop_path(id: sop.id), method: :delete, class: 'badge badge-danger', :data => {confirm: t(:confirm_delete, resource: 'sop')}

app/views/categories/_tree.html.haml
- content_tag :li, :id => dom_id(menu) do
  %span.handle= menu.title
  - content_tag :ul do
    - for child in menu.children do
      = render :partial => "tree", :locals => {:menu => child }
  - end unless menu.leaf?

app/views/categories/edit.html.haml
%nav.navbar.navbar-expand-lg.navbar-light.bg-light
  .container-fluid
    %h3= t(:category_edit)

= render 'form', url: category_path(@category)

app/views/categories/index.html.haml
%nav.navbar.navbar-expand-lg.navbar-light.bg-light
  .container-fluid
    %h3= t(:home)
    = render 'shared/search_form'
    %ul.navbar-nav.ml-auto
      %li.nav-item
        .dropdown
          %button#dropdownMenuButton.btn.btn-primary.dropdown-toggle{ type: :button, 'data-toggle' => :dropdown, 'aria-haspopup' => 'true', 'aria-expanded' => 'false' }
            %i.fa.fa-plus
            &nbsp;
            = t(:new)
          .dropdown-menu{ 'aria-labelledby' => 'dropdownMenuButton' }
            = link_to new_category_path, class: 'dropdown-item' do
              %i.fa.fa-folder
              = t(:category)
            = link_to new_sop_path, class: 'dropdown-item' do
              %i.far.fa-file
              = t(:sop)
    .col-md-1

= render 'breadcrumb'
= render 'item_lists'
= render 'category_modal'

app/views/categories/new.html.haml
%nav.navbar.navbar-expand-lg.navbar-light.bg-light
  .container-fluid
    %h3= t(:category_new)

- url = @category.parent_id ? category_path(@category.parent_id) : categories_path
= render 'form', url: url

app/views/categories/show.html.haml
%nav.navbar.navbar-expand-lg.navbar-light.bg-light
  .container-fluid
    %h3= @category.name
    = render 'shared/search_form'
    %ul.navbar-nav.ml-auto
      %li.nav-item.mx-sm-2
        .dropdown
          %button#dropdownMenuButton.btn.btn-primary.dropdown-toggle{ type: :button, 'data-toggle' => :dropdown, 'aria-haspopup' => 'true', 'aria-expanded' => 'false' }
            %i.fa.fa-plus
            &nbsp;
            = t(:new)
          .dropdown-menu{ 'aria-labelledby' => 'dropdownMenuButton' }
            = link_to new_category_path(parent_id: @category.try(:id)), class: 'dropdown-item' do
              %i.fa.fa-folder
              = t(:category)
            = link_to new_sop_path(category_id: @category.try(:id)), class: 'dropdown-item' do
              %i.far.fa-file
              = t(:sop)

      - if @category.present?
        %li.nav-item.mr-sm-2
          = link_to edit_category_path(@category.id), class: 'btn btn-primary', 'data-toggle' => :tooltip, title: t(:category_edit) do
            %i.fas.fa-pen
      %li.nav-item
        - if @category.nil? || !@category.is_empty?
          %span.d-inline-block{ tabindex: 0, 'data-toggle' => 'tooltip', title: t(:disabled) }
            .btn.btn-secondary{ disabled: true }
              %i.fas.fa-trash-alt
        - else
          = link_to category_path(id: @category.id), method: :delete, class: 'btn btn-danger', :data => {confirm: t(:confirm_delete, resource: 'category'), toggle: 'tooltip', placement: 'bottom'}, title: t(:delete) do
            %i.fas.fa-trash-alt

= render 'breadcrumb'
= render 'item_lists'
= render 'category_modal'